volumes:
  n8n_storage:

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_COMMUNITY_NODES_ENABLED=true
      - N8N_ENABLE_NODE_DEV_ENV=true
    volumes:
      - n8n_storage:/home/node/.n8n
      - /Users/darcy/Desktop/development/invoice_agent/static:/home/node/files
    networks:
      - n8n_network

  fastapi:
    build: ./app
    container_name: api
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
